## Numpy Practice

In [2]:
# import the package
import numpy as np

### Transpose

In [3]:
# 2D Array

dubai = np.array(np.random.randint(10, 45, (8, 2)))
print("Defined array: \n", dubai)
print("Shape of original array:", dubai.shape)

t_dubai = np.transpose(dubai)
print("Transposed array: \n", t_dubai)
print("Shape of tranposed array:", t_dubai.shape)

Defined array: 
 [[24 16]
 [30 28]
 [17 10]
 [10 32]
 [40 40]
 [15 43]
 [38 14]
 [17 25]]
Shape of original array: (8, 2)
Transposed array: 
 [[24 30 17 10 40 15 38 17]
 [16 28 10 32 40 43 14 25]]
Shape of tranposed array: (2, 8)


In [4]:
# 3D Array

arr3d = np.array(np.random.randint(10, 45, (3, 2, 4)))
print("Defined array: \n", arr3d)
print("Shape of original array:", arr3d.shape)

t_arr3d = np.transpose(arr3d)
print("Transposed array: \n", t_arr3d)
print("Shape of tranposed array:", t_arr3d.shape)

Defined array: 
 [[[36 42 33 24]
  [20 26 13 30]]

 [[30 30 15 19]
  [17 37 14 35]]

 [[32 31 15 15]
  [42 30 20 39]]]
Shape of original array: (3, 2, 4)
Transposed array: 
 [[[36 30 32]
  [20 17 42]]

 [[42 30 31]
  [26 37 30]]

 [[33 15 15]
  [13 14 20]]

 [[24 19 15]
  [30 35 39]]]
Shape of tranposed array: (4, 2, 3)


### Reshape

In [5]:
random_cohort = np.array(np.random.randint(10, 45, (3, 8)))
print("Defined array: \n", random_cohort)
print("Shape of defined array:", random_cohort.shape)

Defined array: 
 [[10 29 38 17 26 20 19 25]
 [43 28 39 32 28 41 26 42]
 [21 33 23 18 29 18 32 41]]
Shape of defined array: (3, 8)


In [6]:
new_shape = (2, 6, 2)
reshaped_array = np.reshape(random_cohort, new_shape)
print("Reshaped array: \n", reshaped_array)
print("Shape of reshaped array:", reshaped_array.shape)

Reshaped array: 
 [[[10 29]
  [38 17]
  [26 20]
  [19 25]
  [43 28]
  [39 32]]

 [[28 41]
  [26 42]
  [21 33]
  [23 18]
  [29 18]
  [32 41]]]
Shape of reshaped array: (2, 6, 2)


In [8]:
new_shape2 = (2, -1, 6)
reshaped_array2 = np.reshape(random_cohort, new_shape2)
print("Reshaped array: \n", reshaped_array2)
print("Shape of reshaped array:", reshaped_array2.shape)

Reshaped array: 
 [[[10 29 38 17 26 20]
  [19 25 43 28 39 32]]

 [[28 41 26 42 21 33]
  [23 18 29 18 32 41]]]
Shape of reshaped array: (2, 2, 6)


### Resize

In [11]:
random_3d_cohort = np.array(np.random.randint(10, 45, (2, 4, 6)))
print("Defined array: \n", random_3d_cohort)
print("Shape of defined array:", random_3d_cohort.shape)

Defined array: 
 [[[23 16 26 39 31 35]
  [32 24 22 41 24 38]
  [38 12 16 43 39 24]
  [21 28 15 12 10 36]]

 [[25 42 11 22 10 12]
  [16 40 35 16 21 20]
  [31 34 12 32 31 12]
  [41 22 14 34 10 13]]]
Shape of defined array: (2, 4, 6)


In [13]:
new_shape_res = (2, 3, 6)
resized_arr = np.resize(random_3d_cohort, new_shape_res)
print("Resized array: \n", resized_arr)
print("Shape of resized array:", resized_arr.shape)

Resized array: 
 [[[23 16 26 39 31 35]
  [32 24 22 41 24 38]
  [38 12 16 43 39 24]]

 [[21 28 15 12 10 36]
  [25 42 11 22 10 12]
  [16 40 35 16 21 20]]]
Shape of resized array: (2, 3, 6)


## Pandas Practice

In [1]:
import pandas as pd